# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180502_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_whatsapp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='member',
        ),
    ]
